### ISSUE TITLE
How to run it ?

### ISSUE THREAD

**Issue by Karaulov** [ChiefOfGxBxL/Ice-Sickle#48]
I got error 
![ahyedpx 1](https://user-images.githubusercontent.com/6445336/36352322-28713c54-14c8-11e8-8064-dea45ebc5a13.png)

**Comment by Gaizka-gzgr** [comment]
I have the same issue.

**Comment by ChiefOfGxBxL** [comment]
Hi, thank you for the details. This is an issue with the build system.

Could you please manually install the newly-released version, v0.1.3, to see if the error is resolved?  
https://github.com/ChiefOfGxBxL/Ice-Sickle/releases/tag/v0.1.3

Do let me know if you encounter any similar issues when running 0.1.3. Thanks!

**Comment by ChiefOfGxBxL** [comment]
Sorry for the errors and for my late response. I was moving halfway across the U.S., starting a new job, etc. **I will publish a patch to resolve this issue by Sunday, April 29th**

**Comment by ChiefOfGxBxL** [comment]
I fixed and manually tested a patch for this issue. It is released in [version 0.1.5](https://github.com/ChiefOfGxBxL/Ice-Sickle/releases/tag/v0.1.5). Please install the new version using the link provided to get started.

I'll close this issue, but if anything else comes up feel free to open a new one.
