### ISSUE TITLE
Still don't open

### ISSUE THREAD

**Issue by Gaizka-gzgr** [ChiefOfGxBxL/Ice-Sickle#52]
with release 1.3

![sin titulo](https://user-images.githubusercontent.com/31868874/36804205-26074f9a-1cba-11e8-9ec1-99b387a86454.png)

**Comment by ChiefOfGxBxL** [comment]
Sorry for the errors and for my late response. I was moving halfway across the U.S., starting a new job, etc. 

**I will publish a patch to resolve this issue by Sunday, April 29th**

**Comment by ChiefOfGxBxL** [comment]
I fixed and manually tested a patch for this issue. It is released in [version 0.1.5](https://github.com/ChiefOfGxBxL/Ice-Sickle/releases/tag/v0.1.5). Please install the new version using the link provided to get started.

I'll close this issue, but if anything else comes up feel free to open a new one.
